#!/usr/bin/env bash
# bench-report.sh — Run Criterion benchmarks and produce a versioned JSON snapshot
# Usage: ./scripts/bench-report.sh [output-dir]
#
# Produces:
#   <output-dir>/bench-snapshot-<version>-<date>.json   — structured results
#   <output-dir>/bench-snapshot-<version>-<date>.txt    — human-readable report
#   <output-dir>/bench-latest.json                      — symlink / copy of latest
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="${1:-${REPO_ROOT}/bench-results}"
VERSION="$(grep '^version' "${REPO_ROOT}/Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')"
DATE="$(date -u '+%Y-%m-%d')"
TIMESTAMP="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
COMMIT="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
COMMIT_FULL="$(git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo 'unknown')"

mkdir -p "${OUTPUT_DIR}"

SNAPSHOT_BASE="bench-snapshot-${VERSION}-${DATE}"
JSON_FILE="${OUTPUT_DIR}/${SNAPSHOT_BASE}.json"
TXT_FILE="${OUTPUT_DIR}/${SNAPSHOT_BASE}.txt"
BENCHER_FILE="${OUTPUT_DIR}/bench-bencher-output.txt"

echo "==> Running benchmarks (this may take a few minutes)..."
cargo bench --bench benchmarks -- --output-format bencher 2>/dev/null | tee "${BENCHER_FILE}"

echo ""
echo "==> Parsing results..."

# Parse Criterion's bencher-format output into structured JSON.
# Each line looks like: "test <name> ... bench: <ns> ns/iter (+/- <dev>)"
{
  echo "{"
  echo "  \"version\": \"${VERSION}\","
  echo "  \"date\": \"${DATE}\","
  echo "  \"timestamp\": \"${TIMESTAMP}\","
  echo "  \"commit\": \"${COMMIT_FULL}\","
  echo "  \"commit_short\": \"${COMMIT}\","
  echo "  \"rust_version\": \"$(rustc --version)\","
  echo "  \"os\": \"$(uname -s) $(uname -r)\","
  echo "  \"arch\": \"$(uname -m)\","
  echo "  \"benchmarks\": ["

  FIRST=true
  while IFS= read -r line; do
    # Match: test <name> ... bench:    <ns> ns/iter (+/- <dev>)
    if [[ "${line}" =~ ^test[[:space:]]+(.+)[[:space:]]+\.\.\.[[:space:]]+bench:[[:space:]]+([0-9,]+)[[:space:]]+ns/iter[[:space:]]+\(\+/-[[:space:]]+([0-9,]+)\) ]]; then
      NAME="${BASH_REMATCH[1]}"
      NS="${BASH_REMATCH[2]//,/}"
      DEV="${BASH_REMATCH[3]//,/}"

      if [ "${FIRST}" = "true" ]; then
        FIRST=false
      else
        echo ","
      fi

      printf '    {"name": "%s", "ns_per_iter": %s, "deviation": %s}' \
        "${NAME}" "${NS}" "${DEV}"
    fi
  done < "${BENCHER_FILE}"

  echo ""
  echo "  ]"
  echo "}"
} > "${JSON_FILE}"

# Generate human-readable report.
{
  echo "# Benchmark Report"
  echo ""
  echo "- **Version:** ${VERSION}"
  echo "- **Date:** ${DATE}"
  echo "- **Commit:** ${COMMIT}"
  echo "- **Rust:** $(rustc --version)"
  echo "- **OS:** $(uname -s) $(uname -r) ($(uname -m))"
  echo ""
  echo "| Benchmark | ns/iter | ±deviation | ~throughput |"
  echo "|-----------|---------|------------|-------------|"

  while IFS= read -r line; do
    if [[ "${line}" =~ ^test[[:space:]]+(.+)[[:space:]]+\.\.\.[[:space:]]+bench:[[:space:]]+([0-9,]+)[[:space:]]+ns/iter[[:space:]]+\(\+/-[[:space:]]+([0-9,]+)\) ]]; then
      NAME="${BASH_REMATCH[1]}"
      NS="${BASH_REMATCH[2]//,/}"
      DEV="${BASH_REMATCH[3]//,/}"

      # Compute approximate ops/sec
      if [ "${NS}" -gt 0 ] 2>/dev/null; then
        OPS=$(echo "scale=0; 1000000000 / ${NS}" | bc 2>/dev/null || echo "N/A")
        printf "| %-50s | %'12s | %'12s | %s ops/s |\n" "${NAME}" "${NS}" "${DEV}" "${OPS}"
      else
        printf "| %-50s | %12s | %12s | N/A |\n" "${NAME}" "${NS}" "${DEV}"
      fi
    fi
  done < "${BENCHER_FILE}"

  echo ""
  echo "_Generated by bench-report.sh_"
} > "${TXT_FILE}"

# Copy as latest
cp "${JSON_FILE}" "${OUTPUT_DIR}/bench-latest.json"
cp "${TXT_FILE}" "${OUTPUT_DIR}/bench-latest.txt"

echo ""
echo "==> Snapshot saved:"
echo "    JSON: ${JSON_FILE}"
echo "    Text: ${TXT_FILE}"
echo "    Latest: ${OUTPUT_DIR}/bench-latest.json"
